In [1]:
url = "https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2021-01.csv.gz"

In [37]:
import pandas as pd

In [3]:
import pandas as pantaloons

In [6]:
df = pantaloons.read_csv("https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2021-01.csv.gz");

/tmp/ipykernel_7166/3443405373.py:1: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pantaloons.read_csv("https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2021-01.csv.gz");

In [7]:
df.head()['trip_distance']

0     2.10
1     0.20
2    14.70
3    10.60
4     4.94
Name: trip_distance, dtype: float64

In [8]:
df['trip_distance' < 2]

TypeError: '<' not supported between instances of 'str' and 'int'

In [9]:
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1.0,2021-01-01 00:30:10,2021-01-01 00:36:12,1.0,2.10,1.0,N,142,43,2.0,8.0,3.0,0.5,0.00,0.0,0.3,11.80,2.5
1,1.0,2021-01-01 00:51:20,2021-01-01 00:52:19,1.0,0.20,1.0,N,238,151,2.0,3.0,0.5,0.5,0.00,0.0,0.3,4.30,0.0
2,1.0,2021-01-01 00:43:30,2021-01-01 01:11:06,1.0,14.70,1.0,N,132,165,1.0,42.0,0.5,0.5,8.65,0.0,0.3,51.95,0.0
3,1.0,2021-01-01 00:15:48,2021-01-01 00:31:01,0.0,10.60,1.0,N,138,132,1.0,29.0,0.5,0.5,6.05,0.0,0.3,36.35,0.0
4,2.0,2021-01-01 00:31:49,2021-01-01 00:48:21,1.0,4.94,1.0,N,68,33,1.0,16.5,0.5,0.5,4.06,0.0,0.3,24.36,2.5

In [10]:
len(df['trip_distance'])

1369765

In [11]:
len(df['trip_distance'])

1369765

In [12]:
len(df['trip_distance']  < 2 )

1369765

In [13]:
df['trip_distance'] < 2

0          False
1           True
2          False
3          False
4          False
           ...
1369760    False
1369761    False
1369762    False
1369763    False
1369764    False
Name: trip_distance, Length: 1369765, dtype: bool

0          False
1           True
2          False
3          False
4          False
           ...
1369760    False
1369761    False
1369762    False
1369763    False
1369764    False
Name: trip_distance, Length: 1369765, dtype: bool

In [17]:
dtype = {
    "VendorID": "Int64",
    "passenger_count": "Int64",
    "trip_distance": "float64",
    "RatecodeID": "Int64",
    "store_and_fwd_flag": "string",
    "PULocationID": "Int64",
    "DOLocationID": "Int64",
    "payment_type": "Int64",
    "fare_amount": "float64",
    "extra": "float64",
    "mta_tax": "float64",
    "tip_amount": "float64",
    "tolls_amount": "float64",
    "improvement_surcharge": "float64",
    "total_amount": "float64",
    "congestion_surcharge": "float64"
}

parse_dates = [
    "tpep_pickup_datetime",
    "tpep_dropoff_datetime"
]

df = pantaloons.read_csv(
    url,
    nrows=100,
    dtype=dtype,
    parse_dates=parse_dates
)

In [18]:
df['trip_distance']

0      2.10
1      0.20
2     14.70
3     10.60
4      4.94
      ...
95     4.13
96     4.12
97     2.22
98     7.11
99     1.61
Name: trip_distance, Length: 100, dtype: float64

In [20]:
len(df['trip_distance'])

100

In [21]:
dtype = {
    "VendorID": "Int64",
    "passenger_count": "Int64",
    "trip_distance": "float64",
    "RatecodeID": "Int64",
    "store_and_fwd_flag": "string",
    "PULocationID": "Int64",
    "DOLocationID": "Int64",
    "payment_type": "Int64",
    "fare_amount": "float64",
    "extra": "float64",
    "mta_tax": "float64",
    "tip_amount": "float64",
    "tolls_amount": "float64",
    "improvement_surcharge": "float64",
    "total_amount": "float64",
    "congestion_surcharge": "float64"
}

parse_dates = [
    "tpep_pickup_datetime",
    "tpep_dropoff_datetime"
]

df = pd.read_csv(
    url,
    nrows=100,
    dtype=dtype,
    parse_dates=parse_dates
)

NameError: name 'pd' is not defined

In [22]:
len(df['trip_distance']> 0.0 and df['trip_distance'] < 2.0)

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [26]:
count = ((df['trip_distance'] > 0.0) & (df['trip_distance'] < 2.0)).sum()

In [24]:
count = len(df[df['trip_distance'] < 2])

In [25]:
print(count)

44

In [27]:
count = ((df['trip_distance'] > 0.0) & (df['trip_distance'] < 2.0)).sum()

In [28]:
print(count)

42

In [29]:
df.min();

In [31]:
print(df['trip_distance'].min())

0.0

In [32]:
len(df[df['trip_distance'] == 0.0])

2

In [33]:
count = ((df['trip_distance'] > 0.0) & (df['trip_distance'] < 2.0)).sum()

In [34]:
print(count)

42

In [35]:
!wget https://d37ci6vzurychx.cloudfront.net/trip-data/green_tripdata_2025-11.parquet

--2026-01-26 13:16:14--  https://d37ci6vzurychx.cloudfront.net/trip-data/green_tripdata_2025-11.parquet
Resolving d37ci6vzurychx.cloudfront.net (d37ci6vzurychx.cloudfront.net)... 18.239.115.86, 18.239.115.146, 18.239.115.4, ...
Connecting to d37ci6vzurychx.cloudfront.net (d37ci6vzurychx.cloudfront.net)|18.239.115.86|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1164775 (1.1M) [binary/octet-stream]
Saving to: ‘green_tripdata_2025-11.parquet’

green_tripdata_2025 100%[===================>]   1.11M  --.-KB/s    in 0.02s

2026-01-26 13:16:14 (45.6 MB/s) - ‘green_tripdata_2025-11.parquet’ saved [1164775/1164775]

In [42]:
pandaframe = pd.read_parquet("./green_tripdata_2025-11.parquet");

In [43]:
pandaframe.head();

In [44]:
dfr = pandaframe.head();

In [45]:
print(dft);

NameError: name 'dft' is not defined

In [46]:
print(dfr);

   VendorID lpep_pickup_datetime lpep_dropoff_datetime store_and_fwd_flag  \
0         2  2025-11-01 00:34:48   2025-11-01 00:41:39                  N
1         2  2025-11-01 00:18:52   2025-11-01 00:24:27                  N
2         2  2025-11-01 01:03:14   2025-11-01 01:15:24                  N
3         2  2025-11-01 00:10:57   2025-11-01 00:24:53                  N
4         1  2025-11-01 00:03:48   2025-11-01 00:19:38                  N

   RatecodeID  PULocationID  DOLocationID  passenger_count  trip_distance  \
0         1.0            74            42              1.0           0.74
1         1.0            74            42              2.0           0.95
2         1.0            83           160              1.0           2.19
3         1.0           166           127              1.0           5.44
4         1.0           166           262              1.0           3.20

   fare_amount  ...  mta_tax  tip_amount  tolls_amount  ehail_fee  \
0          7.2  ...      0.5        1.94           0.0        NaN
1          7.2  ...      0.5        0.00           0.0        NaN
2         13.5  ...      0.5        5.00           0.0        NaN
3         24.7  ...      0.5        0.50           0.0        NaN
4         18.4  ...      1.5        1.00           0.0        NaN

   improvement_surcharge  total_amount  payment_type  trip_type  \
0                    1.0         11.64           1.0        1.0
1                    1.0          9.70           2.0        1.0
2                    1.0         21.00           1.0        1.0
3                    1.0         27.70           1.0        1.0
4                    1.0         24.65           1.0        1.0

   congestion_surcharge  cbd_congestion_fee
0                  0.00                 0.0
1                  0.00                 0.0
2                  0.00                 0.0
3                  0.00                 0.0
4                  2.75                 0.0

[5 rows x 21 columns]

In [47]:
(dfr['trip_distance'] > 0.0) & (dfr['trip_distance'] < 2.0)

0     True
1     True
2    False
3    False
4    False
Name: trip_distance, dtype: bool

In [48]:
count = ((dfr['trip_distance'] > 0.0) & (dfr['trip_distance'] < 2.0)).sum()

In [49]:
print(count)

2

In [50]:
len(dfr['trip_distance']);

In [53]:
print(len(dfr['trip_distance']));

5

In [54]:
print(f"Total records: {len(dfr)}")

Total records: 5

In [55]:
!wget https://github.com/DataTalksClub/nyc-tlc-data/releases/download/misc/taxi_zone_lookup.csv

--2026-01-26 13:28:00--  https://github.com/DataTalksClub/nyc-tlc-data/releases/download/misc/taxi_zone_lookup.csv
Resolving github.com (github.com)... 20.207.73.82
Connecting to github.com (github.com)|20.207.73.82|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://release-assets.githubusercontent.com/github-production-release-asset/513814948/5a2cc2f5-b4cd-4584-9c62-a6ea97ed0e6a?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-01-26T14%3A10%3A35Z&rscd=attachment%3B+filename%3Dtaxi_zone_lookup.csv&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-01-26T13%3A09%3A36Z&ske=2026-01-26T14%3A10%3A35Z&sks=b&skv=2018-11-09&sig=RDvVYQ0LC8gs7seWzJ3EzCmprcQI2BX51Jh2NdTL3CU%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc2OTQzNDM4MSwibmJmIjoxNzY5NDM0MDgxLCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.rivDakv0bbSwstvOtFswFyU3S9cM8OIbt2DmXX_EOpg&response-content-disposition=attachment%3B%20filename%3Dtaxi_zone_lookup.csv&response-content-type=application%2Foctet-stream [following]
--2026-01-26 13:28:01--  https://release-assets.githubusercontent.com/github-production-release-asset/513814948/5a2cc2f5-b4cd-4584-9c62-a6ea97ed0e6a?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-01-26T14%3A10%3A35Z&rscd=attachment%3B+filename%3Dtaxi_zone_lookup.csv&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-01-26T13%3A09%3A36Z&ske=2026-01-26T14%3A10%3A35Z&sks=b&skv=2018-11-09&sig=RDvVYQ0LC8gs7seWzJ3EzCmprcQI2BX51Jh2NdTL3CU%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc2OTQzNDM4MSwibmJmIjoxNzY5NDM0MDgxLCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.rivDakv0bbSwstvOtFswFyU3S9cM8OIbt2DmXX_EOpg&response-content-disposition=attachment%3B%20filename%3Dtaxi_zone_lookup.csv&response-content-type=application%2Foctet-stream
Resolving release-assets.githubusercontent.com (release-assets.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.111.133, ...
Connecting to release-assets.githubusercontent.com (release-assets.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 12322 (12K) [application/octet-stream]
Saving to: ‘taxi_zone_lookup.csv’

taxi_zone_lookup.cs 100%[===================>]  12.03K  --.-KB/s    in 0.003s

2026-01-26 13:28:01 (3.88 MB/s) - ‘taxi_zone_lookup.csv’ saved [12322/12322]

In [56]:
import pandas as pdframe

In [57]:
df = pdframe.read_csv(c);

In [58]:
print(df.head());

   LocationID        Borough                     Zone service_zone
0           1            EWR           Newark Airport          EWR
1           2         Queens              Jamaica Bay    Boro Zone
2           3          Bronx  Allerton/Pelham Gardens    Boro Zone
3           4      Manhattan            Alphabet City  Yellow Zone
4           5  Staten Island            Arden Heights    Boro Zone

In [59]:
print(len(df))

265

In [60]:
count(df['pep_pickup_datetime'] > '2025-11-01').sum();

KeyError: 'pep_pickup_datetime'

In [63]:
df.head();

In [64]:
print(df.head());

   LocationID        Borough                     Zone service_zone
0           1            EWR           Newark Airport          EWR
1           2         Queens              Jamaica Bay    Boro Zone
2           3          Bronx  Allerton/Pelham Gardens    Boro Zone
3           4      Manhattan            Alphabet City  Yellow Zone
4           5  Staten Island            Arden Heights    Boro Zone

In [65]:
df.to_csv('../green_tripdata_2025-11.csv', index=False)
print("Converted to CSV: ../green_tripdata_2025-11.csv")

Converted to CSV: ../green_tripdata_2025-11.csv

In [66]:
pcsv = df.read_csv("df.to_csv('../green_tripdata_2025-11.csv', index=False);

SyntaxError: unterminated string literal (detected at line 1) (246966136.py, line 1)

In [67]:
ls

Dockerfile                      nota.ipynb          pyproject.toml
Untitled.ipynb                  nota.py             taxi_zone_lookup.csv
green_tripdata_2025-11.parquet  pipeline-month.py*  uv.lock

In [68]:
df.read_csv("/workspaces/dataclub-dataengineering/data-system/taxi_zone_lookup.csv")

AttributeError: 'DataFrame' object has no attribute 'read_csv'

In [69]:
import pandas as pd

In [70]:
pd.read_csv("/workspaces/dataclub-dataengineering/data-system/taxi_zone_lookup.csv");

In [71]:
csv = pd.read_csv("/workspaces/dataclub-dataengineering/data-system/taxi_zone_lookup.csv");

In [72]:
print(csv.head());

   LocationID        Borough                     Zone service_zone
0           1            EWR           Newark Airport          EWR
1           2         Queens              Jamaica Bay    Boro Zone
2           3          Bronx  Allerton/Pelham Gardens    Boro Zone
3           4      Manhattan            Alphabet City  Yellow Zone
4           5  Staten Island            Arden Heights    Boro Zone

In [2]:
print("Columns in DataFrame:", df.columns.tolist())

NameError: name 'df' is not defined

In [1]:
df.head()

NameError: name 'df' is not defined

In [3]:
import pandas as dfPanda

In [4]:
csv = dfPanda.read_csv("//workspaces/dataclub-dataengineering/green_tripdata_2025-11.csv")

In [5]:
print(csv.head())

   LocationID        Borough                     Zone service_zone
0           1            EWR           Newark Airport          EWR
1           2         Queens              Jamaica Bay    Boro Zone
2           3          Bronx  Allerton/Pelham Gardens    Boro Zone
3           4      Manhattan            Alphabet City  Yellow Zone
4           5  Staten Island            Arden Heights    Boro Zone

In [6]:
rcsv = dfPanda.read_csv("https://github.com/DataTalksClub/nyc-tlc-data/releases/download/misc/taxi_zone_lookup.csv")

In [7]:
print(rcsv.head())

   LocationID        Borough                     Zone service_zone
0           1            EWR           Newark Airport          EWR
1           2         Queens              Jamaica Bay    Boro Zone
2           3          Bronx  Allerton/Pelham Gardens    Boro Zone
3           4      Manhattan            Alphabet City  Yellow Zone
4           5  Staten Island            Arden Heights    Boro Zone

In [8]:
print(csv.head())

   LocationID        Borough                     Zone service_zone
0           1            EWR           Newark Airport          EWR
1           2         Queens              Jamaica Bay    Boro Zone
2           3          Bronx  Allerton/Pelham Gardens    Boro Zone
3           4      Manhattan            Alphabet City  Yellow Zone
4           5  Staten Island            Arden Heights    Boro Zone

In [9]:
!wget https://d37ci6vzurychx.cloudfront.net/trip-data/green_tripdata_2025-11.parquet

--2026-01-26 14:45:51--  https://d37ci6vzurychx.cloudfront.net/trip-data/green_tripdata_2025-11.parquet
Resolving d37ci6vzurychx.cloudfront.net (d37ci6vzurychx.cloudfront.net)... 18.239.115.4, 18.239.115.146, 18.239.115.213, ...
Connecting to d37ci6vzurychx.cloudfront.net (d37ci6vzurychx.cloudfront.net)|18.239.115.4|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1164775 (1.1M) [binary/octet-stream]
Saving to: ‘green_tripdata_2025-11.parquet.1’

green_tripdata_2025 100%[===================>]   1.11M  --.-KB/s    in 0.02s

2026-01-26 14:45:51 (54.3 MB/s) - ‘green_tripdata_2025-11.parquet.1’ saved [1164775/1164775]

In [10]:
!wget https://d37ci6vzurychx.cloudfront.net/trip-data/green_tripdata_2025-11.parquet

--2026-01-26 14:47:17--  https://d37ci6vzurychx.cloudfront.net/trip-data/green_tripdata_2025-11.parquet
Resolving d37ci6vzurychx.cloudfront.net (d37ci6vzurychx.cloudfront.net)... 18.239.115.4, 18.239.115.146, 18.239.115.86, ...
Connecting to d37ci6vzurychx.cloudfront.net (d37ci6vzurychx.cloudfront.net)|18.239.115.4|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1164775 (1.1M) [binary/octet-stream]
Saving to: ‘green_tripdata_2025-11.parquet’

green_tripdata_2025 100%[===================>]   1.11M  --.-KB/s    in 0.03s

2026-01-26 14:47:17 (33.1 MB/s) - ‘green_tripdata_2025-11.parquet’ saved [1164775/1164775]

In [11]:
!wget https://github.com/DataTalksClub/nyc-tlc-data/releases/download/misc/taxi_zone_lookup.csv

--2026-01-26 14:48:14--  https://github.com/DataTalksClub/nyc-tlc-data/releases/download/misc/taxi_zone_lookup.csv
Resolving github.com (github.com)... 20.207.73.82
Connecting to github.com (github.com)|20.207.73.82|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://release-assets.githubusercontent.com/github-production-release-asset/513814948/5a2cc2f5-b4cd-4584-9c62-a6ea97ed0e6a?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-01-26T15%3A36%3A16Z&rscd=attachment%3B+filename%3Dtaxi_zone_lookup.csv&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-01-26T14%3A36%3A14Z&ske=2026-01-26T15%3A36%3A16Z&sks=b&skv=2018-11-09&sig=NywI%2BAhbbQ1hDxKO5qlniteLsDKEpU5ftuhQHIQaI%2FE%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc2OTQzOTE5NCwibmJmIjoxNzY5NDM4ODk0LCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.TXOJG0ULtSYyUZNjZSdhwg34oVHwhQoKu_YXoyGv8T4&response-content-disposition=attachment%3B%20filename%3Dtaxi_zone_lookup.csv&response-content-type=application%2Foctet-stream [following]
--2026-01-26 14:48:14--  https://release-assets.githubusercontent.com/github-production-release-asset/513814948/5a2cc2f5-b4cd-4584-9c62-a6ea97ed0e6a?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-01-26T15%3A36%3A16Z&rscd=attachment%3B+filename%3Dtaxi_zone_lookup.csv&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-01-26T14%3A36%3A14Z&ske=2026-01-26T15%3A36%3A16Z&sks=b&skv=2018-11-09&sig=NywI%2BAhbbQ1hDxKO5qlniteLsDKEpU5ftuhQHIQaI%2FE%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc2OTQzOTE5NCwibmJmIjoxNzY5NDM4ODk0LCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.TXOJG0ULtSYyUZNjZSdhwg34oVHwhQoKu_YXoyGv8T4&response-content-disposition=attachment%3B%20filename%3Dtaxi_zone_lookup.csv&response-content-type=application%2Foctet-stream
Resolving release-assets.githubusercontent.com (release-assets.githubusercontent.com)... 185.199.108.133, 185.199.110.133, 185.199.111.133, ...
Connecting to release-assets.githubusercontent.com (release-assets.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 12322 (12K) [application/octet-stream]
Saving to: ‘taxi_zone_lookup.csv.1’

taxi_zone_lookup.cs 100%[===================>]  12.03K  --.-KB/s    in 0.003s

2026-01-26 14:48:14 (3.98 MB/s) - ‘taxi_zone_lookup.csv.1’ saved [12322/12322]

In [12]:
wget https://github.com/DataTalksClub/nyc-tlc-data/releases/download/misc/taxi_zone_lookup.csv

SyntaxError: invalid syntax (1076730992.py, line 1)

In [13]:
!wget https://github.com/DataTalksClub/nyc-tlc-data/releases/download/misc/taxi_zone_lookup.csv

--2026-01-26 14:48:47--  https://github.com/DataTalksClub/nyc-tlc-data/releases/download/misc/taxi_zone_lookup.csv
Resolving github.com (github.com)... 20.207.73.82
Connecting to github.com (github.com)|20.207.73.82|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://release-assets.githubusercontent.com/github-production-release-asset/513814948/5a2cc2f5-b4cd-4584-9c62-a6ea97ed0e6a?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-01-26T15%3A36%3A16Z&rscd=attachment%3B+filename%3Dtaxi_zone_lookup.csv&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-01-26T14%3A36%3A14Z&ske=2026-01-26T15%3A36%3A16Z&sks=b&skv=2018-11-09&sig=NywI%2BAhbbQ1hDxKO5qlniteLsDKEpU5ftuhQHIQaI%2FE%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc2OTQzOTE5NCwibmJmIjoxNzY5NDM4ODk0LCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.TXOJG0ULtSYyUZNjZSdhwg34oVHwhQoKu_YXoyGv8T4&response-content-disposition=attachment%3B%20filename%3Dtaxi_zone_lookup.csv&response-content-type=application%2Foctet-stream [following]
--2026-01-26 14:48:47--  https://release-assets.githubusercontent.com/github-production-release-asset/513814948/5a2cc2f5-b4cd-4584-9c62-a6ea97ed0e6a?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-01-26T15%3A36%3A16Z&rscd=attachment%3B+filename%3Dtaxi_zone_lookup.csv&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-01-26T14%3A36%3A14Z&ske=2026-01-26T15%3A36%3A16Z&sks=b&skv=2018-11-09&sig=NywI%2BAhbbQ1hDxKO5qlniteLsDKEpU5ftuhQHIQaI%2FE%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc2OTQzOTE5NCwibmJmIjoxNzY5NDM4ODk0LCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.TXOJG0ULtSYyUZNjZSdhwg34oVHwhQoKu_YXoyGv8T4&response-content-disposition=attachment%3B%20filename%3Dtaxi_zone_lookup.csv&response-content-type=application%2Foctet-stream
Resolving release-assets.githubusercontent.com (release-assets.githubusercontent.com)... 185.199.110.133, 185.199.109.133, 185.199.111.133, ...
Connecting to release-assets.githubusercontent.com (release-assets.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 12322 (12K) [application/octet-stream]
Saving to: ‘taxi_zone_lookup.csv’

taxi_zone_lookup.cs 100%[===================>]  12.03K  --.-KB/s    in 0.003s

2026-01-26 14:48:47 (3.41 MB/s) - ‘taxi_zone_lookup.csv’ saved [12322/12322]

In [14]:
import pandas as c

In [16]:
parquet = c.read_parquet("green_tripdata_2025-11.parquet")

In [17]:
csv = c.read_csv("taxi_zone_lookup.csv")

In [18]:
parquet.head();

In [19]:
prqcol = parquet.head();

In [20]:
csvcol = csv.head();

In [22]:
print(prqcol.head());

   VendorID lpep_pickup_datetime lpep_dropoff_datetime store_and_fwd_flag  \
0         2  2025-11-01 00:34:48   2025-11-01 00:41:39                  N
1         2  2025-11-01 00:18:52   2025-11-01 00:24:27                  N
2         2  2025-11-01 01:03:14   2025-11-01 01:15:24                  N
3         2  2025-11-01 00:10:57   2025-11-01 00:24:53                  N
4         1  2025-11-01 00:03:48   2025-11-01 00:19:38                  N

   RatecodeID  PULocationID  DOLocationID  passenger_count  trip_distance  \
0         1.0            74            42              1.0           0.74
1         1.0            74            42              2.0           0.95
2         1.0            83           160              1.0           2.19
3         1.0           166           127              1.0           5.44
4         1.0           166           262              1.0           3.20

   fare_amount  ...  mta_tax  tip_amount  tolls_amount  ehail_fee  \
0          7.2  ...      0.5        1.94           0.0        NaN
1          7.2  ...      0.5        0.00           0.0        NaN
2         13.5  ...      0.5        5.00           0.0        NaN
3         24.7  ...      0.5        0.50           0.0        NaN
4         18.4  ...      1.5        1.00           0.0        NaN

   improvement_surcharge  total_amount  payment_type  trip_type  \
0                    1.0         11.64           1.0        1.0
1                    1.0          9.70           2.0        1.0
2                    1.0         21.00           1.0        1.0
3                    1.0         27.70           1.0        1.0
4                    1.0         24.65           1.0        1.0

   congestion_surcharge  cbd_congestion_fee
0                  0.00                 0.0
1                  0.00                 0.0
2                  0.00                 0.0
3                  0.00                 0.0
4                  2.75                 0.0

[5 rows x 21 columns]

NameError: name 'head' is not defined

In [24]:
len(csvcol['trip_distance']  < 2 )

KeyError: 'trip_distance'

In [28]:
print(prqcol['trip_distance'])

0    0.74
1    0.95
2    2.19
3    5.44
4    3.20
Name: trip_distance, dtype: float64

In [29]:
num_rows = len(prqcol)

5

In [30]:
print(f"Number of rows: {num_rows}")

NameError: name 'num_rows' is not defined

In [31]:
print(prqcol)

   VendorID lpep_pickup_datetime lpep_dropoff_datetime store_and_fwd_flag  \
0         2  2025-11-01 00:34:48   2025-11-01 00:41:39                  N
1         2  2025-11-01 00:18:52   2025-11-01 00:24:27                  N
2         2  2025-11-01 01:03:14   2025-11-01 01:15:24                  N
3         2  2025-11-01 00:10:57   2025-11-01 00:24:53                  N
4         1  2025-11-01 00:03:48   2025-11-01 00:19:38                  N

   RatecodeID  PULocationID  DOLocationID  passenger_count  trip_distance  \
0         1.0            74            42              1.0           0.74
1         1.0            74            42              2.0           0.95
2         1.0            83           160              1.0           2.19
3         1.0           166           127              1.0           5.44
4         1.0           166           262              1.0           3.20

   fare_amount  ...  mta_tax  tip_amount  tolls_amount  ehail_fee  \
0          7.2  ...      0.5        1.94           0.0        NaN
1          7.2  ...      0.5        0.00           0.0        NaN
2         13.5  ...      0.5        5.00           0.0        NaN
3         24.7  ...      0.5        0.50           0.0        NaN
4         18.4  ...      1.5        1.00           0.0        NaN

   improvement_surcharge  total_amount  payment_type  trip_type  \
0                    1.0         11.64           1.0        1.0
1                    1.0          9.70           2.0        1.0
2                    1.0         21.00           1.0        1.0
3                    1.0         27.70           1.0        1.0
4                    1.0         24.65           1.0        1.0

   congestion_surcharge  cbd_congestion_fee
0                  0.00                 0.0
1                  0.00                 0.0
2                  0.00                 0.0
3                  0.00                 0.0
4                  2.75                 0.0

[5 rows x 21 columns]

In [32]:
import pandas as pd; df = pd.read_parquet('data-system/green_tripdata_2025-11.parquet'); print('Columns:', len(df.columns)); print('Rows:', len(df))

FileNotFoundError: [Errno 2] No such file or directory: 'data-system/green_tripdata_2025-11.parquet'

In [34]:
import pandas as pd; df = pd.read_parquet('green_tripdata_2025-11.parquet'); print('Columns:', len(df.columns)); print('Rows:', len(df))

Columns: 21
Rows: 46912

In [35]:
print(df.head())

   VendorID lpep_pickup_datetime lpep_dropoff_datetime store_and_fwd_flag  \
0         2  2025-11-01 00:34:48   2025-11-01 00:41:39                  N
1         2  2025-11-01 00:18:52   2025-11-01 00:24:27                  N
2         2  2025-11-01 01:03:14   2025-11-01 01:15:24                  N
3         2  2025-11-01 00:10:57   2025-11-01 00:24:53                  N
4         1  2025-11-01 00:03:48   2025-11-01 00:19:38                  N

   RatecodeID  PULocationID  DOLocationID  passenger_count  trip_distance  \
0         1.0            74            42              1.0           0.74
1         1.0            74            42              2.0           0.95
2         1.0            83           160              1.0           2.19
3         1.0           166           127              1.0           5.44
4         1.0           166           262              1.0           3.20

   fare_amount  ...  mta_tax  tip_amount  tolls_amount  ehail_fee  \
0          7.2  ...      0.5        1.94           0.0        NaN
1          7.2  ...      0.5        0.00           0.0        NaN
2         13.5  ...      0.5        5.00           0.0        NaN
3         24.7  ...      0.5        0.50           0.0        NaN
4         18.4  ...      1.5        1.00           0.0        NaN

   improvement_surcharge  total_amount  payment_type  trip_type  \
0                    1.0         11.64           1.0        1.0
1                    1.0          9.70           2.0        1.0
2                    1.0         21.00           1.0        1.0
3                    1.0         27.70           1.0        1.0
4                    1.0         24.65           1.0        1.0

   congestion_surcharge  cbd_congestion_fee
0                  0.00                 0.0
1                  0.00                 0.0
2                  0.00                 0.0
3                  0.00                 0.0
4                  2.75                 0.0

[5 rows x 21 columns]

In [36]:
count = ((df['trip_distance'] > 0.0) & (df['trip_distance'] < 2.0)).sum()

In [37]:
print(count) &&

20986

In [41]:
df['lpep_pickup_datetime'] = pd.to_datetime(df['lpep_pickup_datetime'])  
prqcol_november = df[prqcol['lpep_pickup_datetime'].dt.month == 11]

/tmp/ipykernel_7811/3474853373.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  prqcol_november = df[prqcol['lpep_pickup_datetime'].dt.month == 11]

IndexingError: Unalignable boolean Series provided as indexer (index of the boolean Series and of the indexed object do not match).

In [43]:
import pandas as pd

# Ensure the date column is datetime
df['lpep_pickup_datetime'] = pd.to_datetime(df['lpep_pickup_datetime'])

# Filter for November 2025 and trip distance conditions
count = ((df['lpep_pickup_datetime'].dt.month == 11) & 
         (df['lpep_pickup_datetime'].dt.year == 2025) & 
         (df['trip_distance'] > 0.0) & 
         (df['trip_distance'] == 1.0)).sum()

print(f"Count of trips in November 2025 with 0 < trip_distance < 2: {count}")

Count of trips in November 2025 with 0 < trip_distance < 2: 259

In [44]:
df.cols_to_list()

AttributeError: 'DataFrame' object has no attribute 'cols_to_list'

In [45]:
df.columns.tolist()

['VendorID',
 'lpep_pickup_datetime',
 'lpep_dropoff_datetime',
 'store_and_fwd_flag',
 'RatecodeID',
 'PULocationID',
 'DOLocationID',
 'passenger_count',
 'trip_distance',
 'fare_amount',
 'extra',
 'mta_tax',
 'tip_amount',
 'tolls_amount',
 'ehail_fee',
 'improvement_surcharge',
 'total_amount',
 'payment_type',
 'trip_type',
 'congestion_surcharge',
 'cbd_congestion_fee']

In [49]:
df[df['trip_distance'] < 100.0]['lpep_pickup_datetime']

0       2025-11-01 00:34:48
1       2025-11-01 00:18:52
2       2025-11-01 01:03:14
3       2025-11-01 00:10:57
4       2025-11-01 00:03:48
                ...
46907   2025-11-30 19:58:34
46908   2025-11-30 19:34:00
46909   2025-11-30 21:46:46
46910   2025-11-30 21:00:00
46911   2025-11-30 23:26:00
Name: lpep_pickup_datetime, Length: 46891, dtype: datetime64[us]

In [47]:
count = (df['trip_distance'] < 100.0)

In [48]:
print(count)

46891

In [50]:
filtered_df = df[count]

KeyError: np.int64(46891)

In [56]:
 datatable = df[(df['trip_distance'] < 100.0)]

In [52]:
df[(df['trip_distance'] < 100.0)][trip_distance < 1.0]

NameError: name 'trip_distance' is not defined

In [53]:
df[(df['trip_distance'] < 100.0)]['trip_distance' < 1.0]

TypeError: '<' not supported between instances of 'str' and 'float'

In [67]:
df[(df['trip_distance'] < 100.0)]['trip_distance'] < 1.0]

SyntaxError: unmatched ']' (109100261.py, line 1)

In [59]:
datatable[datatable['trip_distance' < 1.0]]

TypeError: '<' not supported between instances of 'str' and 'float'

In [62]:
datatables = datatable['trip_distance'].astype(float)

TypeError: '<' not supported between instances of 'str' and 'float'

In [66]:
datatables.dtypes

dtype('float64')

In [68]:
datatables[datatables['trip_distance'] < 1.0]

KeyError: 'trip_distance'

In [69]:
type(datatables)

pandas.core.series.Series

In [70]:
Dtb = datatables.to_frame(name='trip-distance')

In [71]:
Dtb = datatables.to_frame()

In [72]:
Dtb[Dtb['trip_distance'] < 1.0]

       trip_distance
0               0.74
1               0.95
8               0.63
11              0.00
14              0.00
...              ...
46789           0.95
46809           0.80
46824           0.00
46854           0.79
46876           0.67

[7750 rows x 1 columns]

In [73]:
Dtb[Dtb['trip_distance'] < 1.0].dtypes

trip_distance    float64
dtype: object

In [81]:
Dtab = Dtb[Dtb['trip_distance'] < 100.0]

In [82]:
Dtab = Dtab[Dtab['trip-distance']].max()

KeyError: 'trip-distance'

In [83]:
Dtab['trip_distance'].max()

np.float64(88.03)

In [84]:
print(Dtab['trip_distance'].max())

88.03

In [78]:
print(df.head())

   VendorID lpep_pickup_datetime lpep_dropoff_datetime store_and_fwd_flag  \
0         2  2025-11-01 00:34:48   2025-11-01 00:41:39                  N
1         2  2025-11-01 00:18:52   2025-11-01 00:24:27                  N
2         2  2025-11-01 01:03:14   2025-11-01 01:15:24                  N
3         2  2025-11-01 00:10:57   2025-11-01 00:24:53                  N
4         1  2025-11-01 00:03:48   2025-11-01 00:19:38                  N

   RatecodeID  PULocationID  DOLocationID  passenger_count  trip_distance  \
0         1.0            74            42              1.0           0.74
1         1.0            74            42              2.0           0.95
2         1.0            83           160              1.0           2.19
3         1.0           166           127              1.0           5.44
4         1.0           166           262              1.0           3.20

   fare_amount  ...  mta_tax  tip_amount  tolls_amount  ehail_fee  \
0          7.2  ...      0.5        1.94           0.0        NaN
1          7.2  ...      0.5        0.00           0.0        NaN
2         13.5  ...      0.5        5.00           0.0        NaN
3         24.7  ...      0.5        0.50           0.0        NaN
4         18.4  ...      1.5        1.00           0.0        NaN

   improvement_surcharge  total_amount  payment_type  trip_type  \
0                    1.0         11.64           1.0        1.0
1                    1.0          9.70           2.0        1.0
2                    1.0         21.00           1.0        1.0
3                    1.0         27.70           1.0        1.0
4                    1.0         24.65           1.0        1.0

   congestion_surcharge  cbd_congestion_fee
0                  0.00                 0.0
1                  0.00                 0.0
2                  0.00                 0.0
3                  0.00                 0.0
4                  2.75                 0.0

[5 rows x 21 columns]

In [79]:
df.len()

AttributeError: 'DataFrame' object has no attribute 'len'

In [80]:
len(df)

46912

In [85]:
df.dtypes

VendorID                          int32
lpep_pickup_datetime     datetime64[us]
lpep_dropoff_datetime    datetime64[us]
store_and_fwd_flag               object
RatecodeID                      float64
PULocationID                      int32
DOLocationID                      int32
passenger_count                 float64
trip_distance                   float64
fare_amount                     float64
extra                           float64
mta_tax                         float64
tip_amount                      float64
tolls_amount                    float64
ehail_fee                       float64
improvement_surcharge           float64
total_amount                    float64
payment_type                    float64
trip_type                       float64
congestion_surcharge            float64
cbd_congestion_fee              float64
dtype: object

In [88]:
df[df['trip_distance'] == 88.03]

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,...,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge,cbd_congestion_fee
18867,2,2025-11-14 15:36:27,2025-11-14 18:40:48,N,4.0,130,265,2.0,88.03,610.6,...,0.5,0.0,0.0,NaN,1.0,612.1,2.0,1.0,0.0,0.0

In [89]:
df.head()

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,...,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge,cbd_congestion_fee
0,2,2025-11-01 00:34:48,2025-11-01 00:41:39,N,1.0,74,42,1.0,0.74,7.2,...,0.5,1.94,0.0,NaN,1.0,11.64,1.0,1.0,0.00,0.0
1,2,2025-11-01 00:18:52,2025-11-01 00:24:27,N,1.0,74,42,2.0,0.95,7.2,...,0.5,0.00,0.0,NaN,1.0,9.70,2.0,1.0,0.00,0.0
2,2,2025-11-01 01:03:14,2025-11-01 01:15:24,N,1.0,83,160,1.0,2.19,13.5,...,0.5,5.00,0.0,NaN,1.0,21.00,1.0,1.0,0.00,0.0
3,2,2025-11-01 00:10:57,2025-11-01 00:24:53,N,1.0,166,127,1.0,5.44,24.7,...,0.5,0.50,0.0,NaN,1.0,27.70,1.0,1.0,0.00,0.0
4,1,2025-11-01 00:03:48,2025-11-01 00:19:38,N,1.0,166,262,1.0,3.20,18.4,...,1.5,1.00,0.0,NaN,1.0,24.65,1.0,1.0,2.75,0.0

In [90]:
df['total_amount'].max()

np.float64(991.0)

In [91]:
maxvalue = df['total_amount'].max()

In [95]:
df[df['total_amount'] == 991.0]

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,...,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge,cbd_congestion_fee
21496,2,2025-11-16 13:35:13,2025-11-16 13:35:38,N,5.0,57,57,4.0,0.03,990.0,...,0.0,0.0,0.0,NaN,1.0,991.0,2.0,1.0,0.0,0.0

In [96]:
df.dtypes

VendorID                          int32
lpep_pickup_datetime     datetime64[us]
lpep_dropoff_datetime    datetime64[us]
store_and_fwd_flag               object
RatecodeID                      float64
PULocationID                      int32
DOLocationID                      int32
passenger_count                 float64
trip_distance                   float64
fare_amount                     float64
extra                           float64
mta_tax                         float64
tip_amount                      float64
tolls_amount                    float64
ehail_fee                       float64
improvement_surcharge           float64
total_amount                    float64
payment_type                    float64
trip_type                       float64
congestion_surcharge            float64
cbd_congestion_fee              float64
dtype: object

In [97]:
target_date = pd.to_datetime("2025-11-18").date()

filtered_df = df[df['lpep_pickup_datetime'].dt.date == pd.to_datetime(target_date).date()]

In [98]:
filtered_df[total_amount]

NameError: name 'total_amount' is not defined

In [99]:
filtered_df.dtypes

VendorID                          int32
lpep_pickup_datetime     datetime64[us]
lpep_dropoff_datetime    datetime64[us]
store_and_fwd_flag               object
RatecodeID                      float64
PULocationID                      int32
DOLocationID                      int32
passenger_count                 float64
trip_distance                   float64
fare_amount                     float64
extra                           float64
mta_tax                         float64
tip_amount                      float64
tolls_amount                    float64
ehail_fee                       float64
improvement_surcharge           float64
total_amount                    float64
payment_type                    float64
trip_type                       float64
congestion_surcharge            float64
cbd_congestion_fee              float64
dtype: object

In [101]:
filtered_df.to_string();

In [102]:
print(filtered_df.to_string());

       VendorID lpep_pickup_datetime lpep_dropoff_datetime store_and_fwd_flag  RatecodeID  PULocationID  DOLocationID  passenger_count  trip_distance  fare_amount  extra  mta_tax  tip_amount  tolls_amount  ehail_fee  improvement_surcharge  total_amount  payment_type  trip_type  congestion_surcharge  cbd_congestion_fee
22419         2  2025-11-18 08:07:00   2025-11-18 08:19:15                  N         1.0            74            75              1.0           1.40        12.10   0.00      0.5        3.40          0.00        NaN                    1.0         17.00           1.0        1.0                  0.00                0.00
22420         2  2025-11-18 08:19:54   2025-11-18 08:29:08                  N         1.0            75           236              1.0           1.33        10.00   0.00      0.5        2.85          0.00        NaN                    1.0         17.10           1.0        1.0                  2.75                0.00
22421         2  2025-11-18 08:42:22   2025-11-18 08:53:49                  N         1.0            74           236              1.0           1.97        12.10   0.00      0.5        3.27          0.00        NaN                    1.0         19.62           1.0        1.0                  2.75                0.00
22528         2  2025-11-18 09:08:07   2025-11-18 09:14:44                  N         1.0            74           166              1.0           0.86         7.90   0.00      0.5        1.60          0.00        NaN                    1.0         11.00           1.0        1.0                  0.00                0.00
22529         2  2025-11-18 09:37:57   2025-11-18 09:52:39                  N         1.0            74           116              1.0           2.16        15.60   0.00      0.5        5.13          0.00        NaN                    1.0         22.23           1.0        1.0                  0.00                0.00
22622         2  2025-11-18 10:36:58   2025-11-18 10:57:55                  N         1.0            74           166              1.0           2.48        19.80   0.00      0.5        5.32          0.00        NaN                    1.0         26.62           1.0        1.0                  0.00                0.00
22697         2  2025-11-18 11:36:09   2025-11-18 11:50:08                  N         1.0            74           236              1.0           2.23        14.90   0.00      0.5        3.83          0.00        NaN                    1.0         22.98           1.0        1.0                  2.75                0.00
22793         2  2025-11-18 11:57:19   2025-11-18 12:30:22                  N         1.0            75           229              1.0           3.35        28.20   0.00      0.5        6.64          0.00        NaN                    1.0         39.84           1.0        1.0                  2.75                0.75
23065         2  2025-11-18 15:11:17   2025-11-18 15:20:07                  N         1.0            75            74              1.0           1.49        10.70   0.00      0.5        1.00          0.00        NaN                    1.0         13.20           1.0        1.0                  0.00                0.00
23066         2  2025-11-18 15:23:26   2025-11-18 15:41:50                  N         1.0            74           138              1.0           6.63        29.60   5.00      0.5        8.61          6.94        NaN                    1.0         51.65           1.0        1.0                  0.00                0.00
23165         2  2025-11-18 16:06:14   2025-11-18 16:25:10                  N         1.0            74           263              1.0           2.80        19.10   2.50      0.5        5.17          0.00        NaN                    1.0         31.02           1.0        1.0                  2.75                0.00
23166         2  2025-11-18 16:51:55   2025-11-18 17:01:09                  N         1.0            43           151              1.0           1.34        10.70   2.50      0.5        2.94          0.00        NaN                    1.0         17.64           1.0        1.0                  0.00                0.00
23297         2  2025-11-18 17:12:45   2025-11-18 17:24:11                  N         1.0            75            42              1.0           2.13        12.80   2.50      0.5        2.00          0.00        NaN                    1.0         18.80           1.0        1.0                  0.00                0.00
23298         2  2025-11-18 17:40:36   2025-11-18 17:46:26                  N         1.0            74            41              1.0           0.63         7.20   2.50      0.5        2.24          0.00        NaN                    1.0         13.44           1.0        1.0                  0.00                0.00
23299         2  2025-11-18 17:53:57   2025-11-18 18:08:50                  N         1.0            74           151              1.0           2.31        15.60   2.50      0.5        3.92          0.00        NaN                    1.0         23.52           1.0        1.0                  0.00                0.00
23427         2  2025-11-18 18:41:58   2025-11-18 18:50:58                  N         1.0            74            42              1.0           0.75         9.30   2.50      0.5        5.00          0.00        NaN                    1.0         18.30           1.0        1.0                  0.00                0.00
23525         2  2025-11-18 19:14:28   2025-11-18 19:22:49                  N         1.0            74            41              1.0           1.15        10.00   2.50      0.5        2.80          0.00        NaN                    1.0         16.80           1.0        1.0                  0.00                0.00
23599         2  2025-11-18 20:08:00   2025-11-18 20:14:43                  N         1.0            74           236              1.0           1.62         9.30   1.00      0.5        2.00          0.00        NaN                    1.0         13.80           1.0        1.0                  0.00                0.00
23723         2  2025-11-18 00:19:25   2025-11-18 00:32:41                  N         1.0            41           238              1.0           2.14        14.20   1.00      0.5        3.34          0.00        NaN                    1.0         20.04           1.0        1.0                  0.00                0.00
23724         2  2025-11-18 00:15:31   2025-11-18 00:22:14                  N         1.0            75           263              1.0           1.02         8.60   1.00      0.5        0.00          0.00        NaN                    1.0         13.85           2.0        1.0                  2.75                0.00
23725         2  2025-11-18 00:43:52   2025-11-18 01:00:45                  N         1.0           134           197              1.0           3.55        19.80   1.00      0.5        0.00          0.00        NaN                    1.0         22.30           2.0        1.0                  0.00                0.00
23726         2  2025-11-18 00:36:30   2025-11-18 01:01:00                  N         1.0            83           258              1.0           5.42        28.20   1.00      0.5        0.00          0.00        NaN                    1.0         30.70           2.0        1.0                  0.00                0.00
23727         2  2025-11-18 00:09:41   2025-11-18 00:17:56                  N         1.0            95           196              1.0           1.53        10.00   1.00      0.5        5.00          0.00        NaN                    1.0         17.50           1.0        1.0                  0.00                0.00
23728         2  2025-11-18 00:42:56   2025-11-18 00:46:12                  N         1.0            95            95              1.0           0.81         5.80   1.00      0.5        1.66          0.00        NaN                    1.0          9.96           1.0        1.0                  0.00                0.00
23729         2  2025-11-18 00:08:14   2025-11-18 00:17:48                  N         1.0            95           134              1.0           1.93        12.10   1.00      0.5        0.00          0.00        NaN                    1.0         14.60           2.0        1.0                  0.00                0.00
23730         2  2025-11-18 00:24:58   2025-11-18 00:33:26                  N         1.0            95           160              1.0           2.43        12.80   1.00      0.5        0.00          0.00        NaN                    1.0         15.30           2.0        1.0                  0.00                0.00
23731         2  2025-11-18 00:41:54   2025-11-18 00:41:56                  N         5.0            95           264              1.0           0.00        14.00   0.00      0.0        0.00          0.00        NaN                    1.0         15.00           1.0        2.0                  0.00                0.00
23732         2  2025-11-18 00:38:08   2025-11-18 00:44:20                  N         1.0            75            74              1.0           0.72         6.50   1.00      0.5        0.00          0.00        NaN                    1.0          9.00           1.0        1.0                  0.00                0.00
23733         2  2025-11-18 00:22:39   2025-11-18 00:33:28                  N         1.0           130           205              1.0           2.35        13.50   1.00      0.5        3.20          0.00        NaN                    1.0         19.20           1.0        1.0                  0.00                0.00
23734         2  2025-11-18 01:28:31   2025-11-18 01:35:49                  N         1.0           134           197              1.0           1.82        10.00   1.00      0.5        2.50          0.00        NaN                    1.0         15.00           1.0        1.0                  0.00                0.00
23735         2  2025-11-18 01:05:07   2025-11-18 01:14:19                  N         1.0             7           179              5.0           1.27         9.30   1.00      0.5        2.36          0.00        NaN                    1.0         14.16           1.0        1.0                  0.00                0.00
23736         2  2025-11-18 01:12:15   2025-11-18 01:21:02                  N         1.0            95            56              1.0           1.77        12.10   1.00      0.5        0.00          0.00        NaN                    1.0         14.60           2.0        1.0                  0.00                0.00
23737         2  2025-11-18 01:26:00   2025-11-18 01:31:34                  N         1.0            75           238              5.0           1.15         7.90   1.00      0.5        0.00          0.00        NaN                    1.0         13.15           2.0        1.0                  2.75                0.00
23738         2  2025-11-18 01:21:43   2025-11-18 01:31:46                  N         1.0           130           130              1.0           2.30        13.50   1.00      0.5        1.00          0.00        NaN                    1.0         17.00           1.0        1.0                  0.00                0.00
23739         2  2025-11-18 01:56:25   2025-11-18 02:08:54                  N         1.0           130           218              1.0           5.30        23.30   1.00      0.5        5.16          0.00        NaN                    1.0         30.96           1.0        1.0                  0.00                0.00
23740         2  2025-11-18 01:02:14   2025-11-18 01:19:58                  N         1.0           150           265              1.0          16.32        60.40   1.00      0.5        0.00          0.00        NaN                    1.0         62.90           2.0        1.0                  0.00                0.00
23741         2  2025-11-18 02:28:20   2025-11-18 02:28:34                  N         1.0            95            95              1.0           0.00         3.00   1.00      0.5        0.00          0.00        NaN                    1.0          5.50           2.0        1.0                  0.00                0.00
23742         2  2025-11-18 02:12:36   2025-11-18 02:12:39                  N         5.0            95           264              1.0           0.01         9.00   0.00      0.0        0.00          0.00        NaN                    1.0         10.00           1.0        2.0                  0.00                0.00
23743         2  2025-11-18 03:42:10   2025-11-18 03:53:04                  N         1.0           193           260              1.0           2.80        15.60   1.00      0.5        0.00          0.00        NaN                    1.0         18.10           2.0        1.0                  0.00                0.00
23744         2  2025-11-18 03:25:05   2025-11-18 03:31:18                  N         1.0            75            74              1.0           1.42         9.30   1.00      0.5        0.00          0.00        NaN                    1.0         11.80           2.0        1.0                  0.00                0.00
23745         2  2025-11-18 03:34:54   2025-11-18 03:58:39                  N         1.0            74           248              1.0           5.56        26.80   1.00      0.5       10.00          0.00        NaN                    1.0         39.30           1.0        1.0                  0.00                0.00
23746         2  2025-11-18 03:04:59   2025-11-18 03:05:08                  N         5.0           226           226              4.0           0.00        15.00   0.00      0.0        0.00          0.00        NaN                    1.0         16.00           1.0        1.0                  0.00                0.00
23747         2  2025-11-18 04:05:28   2025-11-18 04:16:20                  N         1.0           129           129              1.0           1.32        11.40   1.00      0.5        2.78          0.00        NaN                    1.0         16.68           1.0        1.0                  0.00                0.00
23748         2  2025-11-18 04:08:09   2025-11-18 04:08:14                  N         5.0            83            83              1.0           0.00        15.00   0.00      0.0        3.20          0.00        NaN                    1.0         19.20           1.0        2.0                  0.00                0.00
23749         2  2025-11-18 04:35:02   2025-11-18 04:37:18                  N         1.0           129           129              1.0           0.21         4.40   1.00      0.5        0.00          0.00        NaN                    1.0          6.90           2.0        1.0                  0.00                0.00
23750         2  2025-11-18 06:01:43   2025-11-18 06:04:54                  N         1.0           260           260              1.0           0.65         5.80   1.00      0.5        0.00          0.00        NaN                    1.0          8.30           2.0        1.0                  0.00                0.00
23751         2  2025-11-18 05:34:25   2025-11-18 05:38:45                  N         1.0            75            41              1.0           0.85         6.50   1.00      0.5        0.00          0.00        NaN                    1.0          9.00           2.0        1.0                  0.00                0.00
23752         2  2025-11-18 05:59:26   2025-11-18 06:16:37                  N         1.0           130           191              1.0           3.67        20.50   1.00      0.5        0.00          0.00        NaN                    1.0         23.00           2.0        1.0                  0.00                0.00
23753         1  2025-11-18 05:53:52   2025-11-18 06:29:17                  N         1.0            55            55              1.0           6.80        36.60   1.00      1.5        0.00          0.00        NaN                    1.0         39.10           2.0        1.0                  0.00                0.00
23754         2  2025-11-18 05:41:34   2025-11-18 05:47:09                  N         1.0            92            53              1.0           1.47         9.30   1.00      0.5        0.04          0.00        NaN                    1.0         11.84           1.0        1.0                  0.00                0.00
23755         1  2025-11-18 05:35:38   2025-11-18 05:42:58                  N         1.0            74            75              1.0           2.20        12.10   1.00      1.5        2.90          0.00        NaN                    1.0         17.50           1.0        1.0                  0.00                0.00
23756         2  2025-11-18 05:43:52   2025-11-18 05:48:45                  N         1.0            74            42              1.0           0.90         7.20   1.00      0.5        1.94          0.00        NaN                    1.0         11.64           1.0        1.0                  0.00                0.00
23757         2  2025-11-18 06:56:05   2025-11-18 07:07:37                  N         1.0            74           159              1.0           1.78        12.80   0.00      0.5        0.00          0.00        NaN                    1.0         14.30           2.0        1.0                  0.00                0.00
23758         1  2025-11-18 06:16:05   2025-11-18 06:24:04                  N         1.0            74           236              1.0           2.00        10.70   2.75      1.5        3.70          0.00        NaN                    1.0         18.65           1.0        1.0                  2.75                0.00
23759         1  2025-11-18 06:39:40   2025-11-18 06:53:36                  N         1.0            74           244              1.0           2.80        15.60   0.00      1.5        3.40          0.00        NaN                    1.0         20.50           1.0        1.0                  0.00                0.00
23760         2  2025-11-18 06:36:31   2025-11-18 06:43:00                  N         1.0            74           236              1.0           1.83         9.30   0.00      0.5        2.03          0.00        NaN                    1.0         15.58           1.0        1.0                  2.75                0.00
23761         2  2025-11-18 06:37:23   2025-11-18 06:45:27                  N         1.0            74           236              1.0           1.61        10.00   0.00      0.5        1.42          0.00        NaN                    1.0         15.67           1.0        1.0                  2.75                0.00
23762         2  2025-11-18 06:17:42   2025-11-18 06:29:31                  N         1.0            74           138              1.0           6.52        26.80   5.00      0.5        8.05          6.94        NaN                    1.0         48.29           1.0        1.0                  0.00                0.00
23763         2  2025-11-18 06:57:28   2025-11-18 07:03:23                  N         1.0            74            74              1.0           0.78         7.20   0.00      0.5        1.00          0.00        NaN                    1.0          9.70           1.0        1.0                  0.00                0.00
23764         2  2025-11-18 06:57:47   2025-11-18 07:07:22                  N         1.0            74           236              1.0           2.05        11.40   0.00      0.5        3.13          0.00        NaN                    1.0         18.78           1.0        1.0                  2.75                0.00
23765         2  2025-11-18 06:29:17   2025-11-18 06:50:04                  N         1.0            41           140              1.0           4.31        24.70   0.00      0.5        2.00          0.00        NaN                    1.0         30.95           1.0        1.0                  2.75                0.00

In [106]:
summ = filtered_df['total_amount'].sum();

In [107]:
print(summ)

45845.909999999996

In [108]:
filtered_dt['lpep_pickup_datetime']

NameError: name 'filtered_dt' is not defined

In [110]:
filtered_df['lpep_pickup_datetime']

22419   2025-11-18 08:07:00
22420   2025-11-18 08:19:54
22421   2025-11-18 08:42:22
22528   2025-11-18 09:08:07
22529   2025-11-18 09:37:57
                ...
44825   2025-11-18 20:42:28
44826   2025-11-18 20:50:43
44827   2025-11-18 20:25:00
44828   2025-11-18 22:38:00
44829   2025-11-18 22:21:00
Name: lpep_pickup_datetime, Length: 1773, dtype: datetime64[us]

In [111]:
df['date'] = filtered_df['lpep_pickup_datetime'].dt.date
target_date = df.groupby('date')['total_amount'].sum().idxmax()
fi_df = df[df['date'] == target_date]

print(fi_df)

       VendorID lpep_pickup_datetime lpep_dropoff_datetime store_and_fwd_flag  \
22419         2  2025-11-18 08:07:00   2025-11-18 08:19:15                  N
22420         2  2025-11-18 08:19:54   2025-11-18 08:29:08                  N
22421         2  2025-11-18 08:42:22   2025-11-18 08:53:49                  N
22528         2  2025-11-18 09:08:07   2025-11-18 09:14:44                  N
22529         2  2025-11-18 09:37:57   2025-11-18 09:52:39                  N
...         ...                  ...                   ...                ...
44825         6  2025-11-18 20:42:28   2025-11-18 21:30:50               None
44826         6  2025-11-18 20:50:43   2025-11-18 22:03:03               None
44827         2  2025-11-18 20:25:00   2025-11-18 20:50:00               None
44828         2  2025-11-18 22:38:00   2025-11-18 22:47:00               None
44829         2  2025-11-18 22:21:00   2025-11-18 22:34:00               None

       RatecodeID  PULocationID  DOLocationID  passenger_count  trip_distance  \
22419         1.0            74            75              1.0           1.40
22420         1.0            75           236              1.0           1.33
22421         1.0            74           236              1.0           1.97
22528         1.0            74           166              1.0           0.86
22529         1.0            74           116              1.0           2.16
...           ...           ...           ...              ...            ...
44825         NaN           236           123              NaN          16.14
44826         NaN           263            61              NaN          12.55
44827         NaN           244           249              NaN           8.54
44828         NaN           166            74              NaN           1.76
44829         NaN            97           148              NaN           2.66

       fare_amount  ...  tip_amount  tolls_amount  ehail_fee  \
22419        12.10  ...        3.40          0.00        NaN
22420        10.00  ...        2.85          0.00        NaN
22421        12.10  ...        3.27          0.00        NaN
22528         7.90  ...        1.60          0.00        NaN
22529        15.60  ...        5.13          0.00        NaN
...            ...  ...         ...           ...        ...
44825         2.90  ...        0.00          6.94        NaN
44826         2.90  ...        0.00          0.00        NaN
44827        40.07  ...        9.01          0.00        NaN
44828        16.44  ...        3.59          0.00        NaN
44829        20.77  ...        3.61          0.00        NaN

       improvement_surcharge  total_amount  payment_type  trip_type  \
22419                    1.0         17.00           1.0        1.0
22420                    1.0         17.10           1.0        1.0
22421                    1.0         19.62           1.0        1.0
22528                    1.0         11.00           1.0        1.0
22529                    1.0         22.23           1.0        1.0
...                      ...           ...           ...        ...
44825                    0.3         46.87           NaN        NaN
44826                    0.3         42.40           NaN        NaN
44827                    1.0         54.08           NaN        NaN
44828                    1.0         21.53           NaN        NaN
44829                    1.0         29.38           NaN        NaN

       congestion_surcharge  cbd_congestion_fee        date
22419                  0.00                0.00  2025-11-18
22420                  2.75                0.00  2025-11-18
22421                  2.75                0.00  2025-11-18
22528                  0.00                0.00  2025-11-18
22529                  0.00                0.00  2025-11-18
...                     ...                 ...         ...
44825                   NaN                0.00  2025-11-18
44826                   NaN                0.00  2025-11-18
44827                   NaN                0.75  2025-11-18
44828                   NaN                0.00  2025-11-18
44829                   NaN                0.75  2025-11-18

[1773 rows x 22 columns]

In [112]:
fi_df.dtypes

VendorID                          int32
lpep_pickup_datetime     datetime64[us]
lpep_dropoff_datetime    datetime64[us]
store_and_fwd_flag               object
RatecodeID                      float64
PULocationID                      int32
DOLocationID                      int32
passenger_count                 float64
trip_distance                   float64
fare_amount                     float64
extra                           float64
mta_tax                         float64
tip_amount                      float64
tolls_amount                    float64
ehail_fee                       float64
improvement_surcharge           float64
total_amount                    float64
payment_type                    float64
trip_type                       float64
congestion_surcharge            float64
cbd_congestion_fee              float64
date                             object
dtype: object

In [113]:
rscv.head()

NameError: name 'rscv' is not defined

In [114]:
rcsv.head()

   LocationID        Borough                     Zone service_zone
0           1            EWR           Newark Airport          EWR
1           2         Queens              Jamaica Bay    Boro Zone
2           3          Bronx  Allerton/Pelham Gardens    Boro Zone
3           4      Manhattan            Alphabet City  Yellow Zone
4           5  Staten Island            Arden Heights    Boro Zone

In [115]:
rsv.to_string()

NameError: name 'rsv' is not defined

In [117]:
print(rcsv.to_string());

     LocationID        Borough                                           Zone service_zone
0             1            EWR                                 Newark Airport          EWR
1             2         Queens                                    Jamaica Bay    Boro Zone
2             3          Bronx                        Allerton/Pelham Gardens    Boro Zone
3             4      Manhattan                                  Alphabet City  Yellow Zone
4             5  Staten Island                                  Arden Heights    Boro Zone
5             6  Staten Island                        Arrochar/Fort Wadsworth    Boro Zone
6             7         Queens                                        Astoria    Boro Zone
7             8         Queens                                   Astoria Park    Boro Zone
8             9         Queens                                     Auburndale    Boro Zone
9            10         Queens                                   Baisley Park    Boro Zone
10           11       Brooklyn                                     Bath Beach    Boro Zone
11           12      Manhattan                                   Battery Park  Yellow Zone
12           13      Manhattan                              Battery Park City  Yellow Zone
13           14       Brooklyn                                      Bay Ridge    Boro Zone
14           15         Queens                        Bay Terrace/Fort Totten    Boro Zone
15           16         Queens                                        Bayside    Boro Zone
16           17       Brooklyn                                        Bedford    Boro Zone
17           18          Bronx                                   Bedford Park    Boro Zone
18           19         Queens                                      Bellerose    Boro Zone
19           20          Bronx                                        Belmont    Boro Zone
20           21       Brooklyn                               Bensonhurst East    Boro Zone
21           22       Brooklyn                               Bensonhurst West    Boro Zone
22           23  Staten Island                        Bloomfield/Emerson Hill    Boro Zone
23           24      Manhattan                                   Bloomingdale  Yellow Zone
24           25       Brooklyn                                    Boerum Hill    Boro Zone
25           26       Brooklyn                                   Borough Park    Boro Zone
26           27         Queens            Breezy Point/Fort Tilden/Riis Beach    Boro Zone
27           28         Queens                        Briarwood/Jamaica Hills    Boro Zone
28           29       Brooklyn                                 Brighton Beach    Boro Zone
29           30         Queens                                  Broad Channel    Boro Zone
30           31          Bronx                                     Bronx Park    Boro Zone
31           32          Bronx                                      Bronxdale    Boro Zone
32           33       Brooklyn                               Brooklyn Heights    Boro Zone
33           34       Brooklyn                             Brooklyn Navy Yard    Boro Zone
34           35       Brooklyn                                    Brownsville    Boro Zone
35           36       Brooklyn                                 Bushwick North    Boro Zone
36           37       Brooklyn                                 Bushwick South    Boro Zone
37           38         Queens                                Cambria Heights    Boro Zone
38           39       Brooklyn                                       Canarsie    Boro Zone
39           40       Brooklyn                                Carroll Gardens    Boro Zone
40           41      Manhattan                                 Central Harlem    Boro Zone
41           42      Manhattan                           Central Harlem North    Boro Zone
42           43      Manhattan                                   Central Park  Yellow Zone
43           44  Staten Island                         Charleston/Tottenville    Boro Zone
44           45      Manhattan                                      Chinatown  Yellow Zone
45           46          Bronx                                    City Island    Boro Zone
46           47          Bronx                             Claremont/Bathgate    Boro Zone
47           48      Manhattan                                   Clinton East  Yellow Zone
48           49       Brooklyn                                   Clinton Hill    Boro Zone
49           50      Manhattan                                   Clinton West  Yellow Zone
50           51          Bronx                                     Co-Op City    Boro Zone
51           52       Brooklyn                                    Cobble Hill    Boro Zone
52           53         Queens                                  College Point    Boro Zone
53           54       Brooklyn                                Columbia Street    Boro Zone
54           55       Brooklyn                                   Coney Island    Boro Zone
55           56         Queens                                         Corona    Boro Zone
56           57         Queens                                         Corona    Boro Zone
57           58          Bronx                                   Country Club    Boro Zone
58           59          Bronx                                   Crotona Park    Boro Zone
59           60          Bronx                              Crotona Park East    Boro Zone
60           61       Brooklyn                            Crown Heights North    Boro Zone
61           62       Brooklyn                            Crown Heights South    Boro Zone
62           63       Brooklyn                                  Cypress Hills    Boro Zone
63           64         Queens                                     Douglaston    Boro Zone
64           65       Brooklyn                    Downtown Brooklyn/MetroTech    Boro Zone
65           66       Brooklyn                             DUMBO/Vinegar Hill    Boro Zone
66           67       Brooklyn                                  Dyker Heights    Boro Zone
67           68      Manhattan                                   East Chelsea  Yellow Zone
68           69          Bronx               East Concourse/Concourse Village    Boro Zone
69           70         Queens                                  East Elmhurst    Boro Zone
70           71       Brooklyn                         East Flatbush/Farragut    Boro Zone
71           72       Brooklyn                   East Flatbush/Remsen Village    Boro Zone
72           73         Queens                                  East Flushing    Boro Zone
73           74      Manhattan                              East Harlem North    Boro Zone
74           75      Manhattan                              East Harlem South    Boro Zone
75           76       Brooklyn                                  East New York    Boro Zone
76           77       Brooklyn              East New York/Pennsylvania Avenue    Boro Zone
77           78          Bronx                                   East Tremont    Boro Zone
78           79      Manhattan                                   East Village  Yellow Zone
79           80       Brooklyn                              East Williamsburg    Boro Zone
80           81          Bronx                                    Eastchester    Boro Zone
81           82         Queens                                       Elmhurst    Boro Zone
82           83         Queens                               Elmhurst/Maspeth    Boro Zone
83           84  Staten Island              Eltingville/Annadale/Prince's Bay    Boro Zone
84           85       Brooklyn                                        Erasmus    Boro Zone
85           86         Queens                                   Far Rockaway    Boro Zone
86           87      Manhattan                       Financial District North  Yellow Zone
87           88      Manhattan                       Financial District South  Yellow Zone
88           89       Brooklyn                           Flatbush/Ditmas Park    Boro Zone
89           90      Manhattan                                       Flatiron  Yellow Zone
90           91       Brooklyn                                      Flatlands    Boro Zone
91           92         Queens                                       Flushing    Boro Zone
92           93         Queens                   Flushing Meadows-Corona Park    Boro Zone
93           94          Bronx                                  Fordham South    Boro Zone
94           95         Queens                                   Forest Hills    Boro Zone
95           96         Queens                      Forest Park/Highland Park    Boro Zone
96           97       Brooklyn                                    Fort Greene    Boro Zone
97           98         Queens                                  Fresh Meadows    Boro Zone
98           99  Staten Island                                Freshkills Park    Boro Zone
99          100      Manhattan                               Garment District  Yellow Zone
100         101         Queens                                      Glen Oaks    Boro Zone
101         102         Queens                                       Glendale    Boro Zone
102         103      Manhattan  Governor's Island/Ellis Island/Liberty Island  Yellow Zone
103         104      Manhattan  Governor's Island/Ellis Island/Liberty Island  Yellow Zone
104         105      Manhattan  Governor's Island/Ellis Island/Liberty Island  Yellow Zone
105         106       Brooklyn                                        Gowanus    Boro Zone
106         107      Manhattan                                       Gramercy  Yellow Zone
107         108       Brooklyn                                      Gravesend    Boro Zone
108         109  Staten Island                                    Great Kills    Boro Zone
109         110  Staten Island                               Great Kills Park    Boro Zone
110         111       Brooklyn                            Green-Wood Cemetery    Boro Zone
111         112       Brooklyn                                     Greenpoint    Boro Zone
112         113      Manhattan                        Greenwich Village North  Yellow Zone
113         114      Manhattan                        Greenwich Village South  Yellow Zone
114         115  Staten Island                            Grymes Hill/Clifton    Boro Zone
115         116      Manhattan                               Hamilton Heights    Boro Zone
116         117         Queens                                Hammels/Arverne    Boro Zone
117         118  Staten Island                    Heartland Village/Todt Hill    Boro Zone
118         119          Bronx                                     Highbridge    Boro Zone
119         120      Manhattan                                Highbridge Park    Boro Zone
120         121         Queens                              Hillcrest/Pomonok    Boro Zone
121         122         Queens                                         Hollis    Boro Zone
122         123       Brooklyn                                      Homecrest    Boro Zone
123         124         Queens                                   Howard Beach    Boro Zone
124         125      Manhattan                                      Hudson Sq  Yellow Zone
125         126          Bronx                                    Hunts Point    Boro Zone
126         127      Manhattan                                         Inwood    Boro Zone
127         128      Manhattan                               Inwood Hill Park    Boro Zone
128         129         Queens                                Jackson Heights    Boro Zone
129         130         Queens                                        Jamaica    Boro Zone
130         131         Queens                                Jamaica Estates    Boro Zone
131         132         Queens                                    JFK Airport     Airports
132         133       Brooklyn                                     Kensington    Boro Zone
133         134         Queens                                    Kew Gardens    Boro Zone
134         135         Queens                              Kew Gardens Hills    Boro Zone
135         136          Bronx                            Kingsbridge Heights    Boro Zone
136         137      Manhattan                                       Kips Bay  Yellow Zone
137         138         Queens                              LaGuardia Airport     Airports
138         139         Queens                                      Laurelton    Boro Zone
139         140      Manhattan                                Lenox Hill East  Yellow Zone
140         141      Manhattan                                Lenox Hill West  Yellow Zone
141         142      Manhattan                            Lincoln Square East  Yellow Zone
142         143      Manhattan                            Lincoln Square West  Yellow Zone
143         144      Manhattan                            Little Italy/NoLiTa  Yellow Zone
144         145         Queens                 Long Island City/Hunters Point    Boro Zone
145         146         Queens                  Long Island City/Queens Plaza    Boro Zone
146         147          Bronx                                       Longwood    Boro Zone
147         148      Manhattan                                Lower East Side  Yellow Zone
148         149       Brooklyn                                        Madison    Boro Zone
149         150       Brooklyn                                Manhattan Beach    Boro Zone
150         151      Manhattan                               Manhattan Valley  Yellow Zone
151         152      Manhattan                                 Manhattanville    Boro Zone
152         153      Manhattan                                    Marble Hill    Boro Zone
153         154       Brooklyn                Marine Park/Floyd Bennett Field    Boro Zone
154         155       Brooklyn                         Marine Park/Mill Basin    Boro Zone
155         156  Staten Island                                Mariners Harbor    Boro Zone
156         157         Queens                                        Maspeth    Boro Zone
157         158      Manhattan                  Meatpacking/West Village West  Yellow Zone
158         159          Bronx                                  Melrose South    Boro Zone
159         160         Queens                                 Middle Village    Boro Zone
160         161      Manhattan                                 Midtown Center  Yellow Zone
161         162      Manhattan                                   Midtown East  Yellow Zone
162         163      Manhattan                                  Midtown North  Yellow Zone
163         164      Manhattan                                  Midtown South  Yellow Zone
164         165       Brooklyn                                        Midwood    Boro Zone
165         166      Manhattan                            Morningside Heights    Boro Zone
166         167          Bronx                             Morrisania/Melrose    Boro Zone
167         168          Bronx                         Mott Haven/Port Morris    Boro Zone
168         169          Bronx                                     Mount Hope    Boro Zone
169         170      Manhattan                                    Murray Hill  Yellow Zone
170         171         Queens                             Murray Hill-Queens    Boro Zone
171         172  Staten Island                         New Dorp/Midland Beach    Boro Zone
172         173         Queens                                   North Corona    Boro Zone
173         174          Bronx                                        Norwood    Boro Zone
174         175         Queens                                Oakland Gardens    Boro Zone
175         176  Staten Island                                        Oakwood    Boro Zone
176         177       Brooklyn                                     Ocean Hill    Boro Zone
177         178       Brooklyn                            Ocean Parkway South    Boro Zone
178         179         Queens                                    Old Astoria    Boro Zone
179         180         Queens                                     Ozone Park    Boro Zone
180         181       Brooklyn                                     Park Slope    Boro Zone
181         182          Bronx                                    Parkchester    Boro Zone
182         183          Bronx                                     Pelham Bay    Boro Zone
183         184          Bronx                                Pelham Bay Park    Boro Zone
184         185          Bronx                                 Pelham Parkway    Boro Zone
185         186      Manhattan                   Penn Station/Madison Sq West  Yellow Zone
186         187  Staten Island                                  Port Richmond    Boro Zone
187         188       Brooklyn                      Prospect-Lefferts Gardens    Boro Zone
188         189       Brooklyn                               Prospect Heights    Boro Zone
189         190       Brooklyn                                  Prospect Park    Boro Zone
190         191         Queens                                 Queens Village    Boro Zone
191         192         Queens                                Queensboro Hill    Boro Zone
192         193         Queens                        Queensbridge/Ravenswood    Boro Zone
193         194      Manhattan                                Randalls Island  Yellow Zone
194         195       Brooklyn                                       Red Hook    Boro Zone
195         196         Queens                                      Rego Park    Boro Zone
196         197         Queens                                  Richmond Hill    Boro Zone
197         198         Queens                                      Ridgewood    Boro Zone
198         199          Bronx                                  Rikers Island    Boro Zone
199         200          Bronx            Riverdale/North Riverdale/Fieldston    Boro Zone
200         201         Queens                                  Rockaway Park    Boro Zone
201         202      Manhattan                               Roosevelt Island    Boro Zone
202         203         Queens                                       Rosedale    Boro Zone
203         204  Staten Island                              Rossville/Woodrow    Boro Zone
204         205         Queens                                   Saint Albans    Boro Zone
205         206  Staten Island                      Saint George/New Brighton    Boro Zone
206         207         Queens               Saint Michaels Cemetery/Woodside    Boro Zone
207         208          Bronx                   Schuylerville/Edgewater Park    Boro Zone
208         209      Manhattan                                        Seaport  Yellow Zone
209         210       Brooklyn                                 Sheepshead Bay    Boro Zone
210         211      Manhattan                                           SoHo  Yellow Zone
211         212          Bronx                             Soundview/Bruckner    Boro Zone
212         213          Bronx                          Soundview/Castle Hill    Boro Zone
213         214  Staten Island                       South Beach/Dongan Hills    Boro Zone
214         215         Queens                                  South Jamaica    Boro Zone
215         216         Queens                               South Ozone Park    Boro Zone
216         217       Brooklyn                             South Williamsburg    Boro Zone
217         218         Queens                      Springfield Gardens North    Boro Zone

In [118]:
rsv.dtypes

NameError: name 'rsv' is not defined

In [119]:
print(rsv);

NameError: name 'rsv' is not defined

In [120]:
rcsv.dtypes()

TypeError: 'Series' object is not callable

In [121]:
rcsv.dtype();

AttributeError: 'DataFrame' object has no attribute 'dtype'

In [122]:
rcsv.head();

In [123]:
rcsv[rcsv['LocationID' == 57]]

KeyError: False

In [125]:
rcsv[LocationID == 57].head()

NameError: name 'LocationID' is not defined

In [126]:
rcsv[LocationID == 57]

NameError: name 'LocationID' is not defined

In [127]:
rcsv.head()

   LocationID        Borough                     Zone service_zone
0           1            EWR           Newark Airport          EWR
1           2         Queens              Jamaica Bay    Boro Zone
2           3          Bronx  Allerton/Pelham Gardens    Boro Zone
3           4      Manhattan            Alphabet City  Yellow Zone
4           5  Staten Island            Arden Heights    Boro Zone

In [128]:
rcsv.columnstoList();

AttributeError: 'DataFrame' object has no attribute 'columnstoList'

In [129]:
df[df['LocationID'] == 30]

KeyError: 'LocationID'

In [130]:
rcsv.dtypes

LocationID       int64
Borough         object
Zone            object
service_zone    object
dtype: object

In [131]:
rcsv.columns.tolist()

['LocationID', 'Borough', 'Zone', 'service_zone']

In [134]:
rcsv[rcsv['LocationID'] == 57]

    LocationID Borough    Zone service_zone
56          57  Queens  Corona    Boro Zone

In [135]:
zone_grouped = filtered_df.groupby('PULocationID')['total_amount'].sum()

In [136]:
largest_zone = zone_grouped.idxmax()   # gives the zone name/ID
largest_value = zone_grouped.max()     # gives the sum value

print("Pickup zone with largest total:", largest_zone, "Sum:", largest_value)

Pickup zone with largest total: 74 Sum: 9281.92

In [137]:
print(largest_zone)

74

In [139]:
zone_df = rcsv[rcsv['Zone'] == largest_zone]

In [140]:
print(zone_df.head())

Empty DataFrame
Columns: [LocationID, Borough, Zone, service_zone]
Index: []

In [141]:
rcsv[rcsv[Location_ID] == 74]

NameError: name 'Location_ID' is not defined

In [142]:
rcsv[rcsv['LocationID'] == 74]

    LocationID    Borough               Zone service_zone
73          74  Manhattan  East Harlem North    Boro Zone

In [143]:
filtered_data[filtered_data == 74]

NameError: name 'filtered_data' is not defined

In [144]:
filtered_data[LocationID == 74]

NameError: name 'filtered_data' is not defined

In [147]:
filtered_df['LocationID' == 74]

KeyError: False

In [148]:
filtered_df['LocationID' == 74]

KeyError: False

In [152]:
df_filter = filtered_df[filtered_df['PULocationID'] == 74]

In [153]:
filtered_nov = df_filter[df_filter['lpep_pickup_datetime'].dt.month == 11]

In [154]:
filtered_nov.dtypes

VendorID                          int32
lpep_pickup_datetime     datetime64[us]
lpep_dropoff_datetime    datetime64[us]
store_and_fwd_flag               object
RatecodeID                      float64
PULocationID                      int32
DOLocationID                      int32
passenger_count                 float64
trip_distance                   float64
fare_amount                     float64
extra                           float64
mta_tax                         float64
tip_amount                      float64
tolls_amount                    float64
ehail_fee                       float64
improvement_surcharge           float64
total_amount                    float64
payment_type                    float64
trip_type                       float64
congestion_surcharge            float64
cbd_congestion_fee              float64
dtype: object

In [155]:
largest_trip_df = filtered_nov.loc[[filtered_nov['trip_distance'].idxmax()]]

In [156]:
largeest_trip_df.head()

NameError: name 'largeest_trip_df' is not defined